production:
    adapter: postgresql
    database: docs
    username: docs
    password: k*312bx01935j
    encoding: unicode
    host: localhost
    pool: 5
development:
    adapter: sqlite3
    database: db/development.sqlite3
    timeout: 5000
